### ISSUE TITLE
Allow change all matched replacements in selection

### ISSUE THREAD

**Issue by lardissone** [MambaDev/Toggler#5]
I use the extension mostly for changing from double quotes to single quotes in current `"string"`. But doing it by every `"` is slow, even if you do a multi cursor selection.

Make a setting to allow changing all matches in selected text, so that if I select: `"string"` and press the shortcut it will switch to all combinations of `"`, or if there's a match to the entire selection, do the same.

```js
"string"
// to
'string'
// to
`string`
// to 
"another-string"   // if any
```

**Comment by tehstun** [comment]
Thank you, its on the list!
